name: Update Pull Request environment

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  PR_NUMBER: ${{ github.event.number }}
  PROJECT: ${{ github.event.repository.name }}
  SHA: ${{ github.sha }}
  TAG: ${{ github.event.repository.name }}-pr${{ github.event.number }}-${{ github.sha }}

jobs:
  image-build:
    name: Build container image
    runs-on: ubuntu-24.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image with the latest tag and the release tag
      - name: Build and push Docker image with release tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: uugai/pullrequests:${{ env.TAG }}

  format:
    name: Print Pull Request Info
    runs-on: ubuntu-24.04
    needs: image-build
    steps:
      # Print out the pull request event type
      - name: Print out pull request event type
        run: |
          echo Pull request event: ${{ github.event.action }}

  update-pr-environment:
    name: Update Pull Request environment in GitOps repo
    runs-on: ubuntu-24.04
    needs: format
    steps:
      # After we build the Docker image, we create a pull request to update the GitOps repository
      # This will allow us to update the Helm chart with the new Docker image tag.

      - name: Update GitOps Pull Request environment
        uses: cedricve/gitops-pullrequest-environment@main
        with:
          # Pass through the GitHub PR action (opened, synchronize, closed)
          # Based on this action, we can determine if we need to create a new environment or update an existing one.
          action: ${{ github.event.action }}
          github-token: ${{ secrets.TOKEN }}
          gitops-repo: "uug-ai/gitops"
          gitops-project: ${{ env.PROJECT }}
          gitops-pr-environment: "pr${{ env.PR_NUMBER }}"
          changes: |
            {
              "images[0].newName": "uugai/pullrequests",
              "images[0].newTag": "${{ env.TAG }}"
            }
          commit-email: "gitops@uug.ai"
          commit-name: "GitOps - UUG.AI"
          commit-message: "Adapating pull request environment for ${{ env.PROJECT }} for pr${{ env.PR_NUMBER }}"
