name: Create a new release
on:
  release:
    types: [created]

env:
  ORGANIZATION: uugai
  REPO: "documentation"
  REPO_SHORT: "documentation"

jobs:

  build-amd64:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      matrix:
        architecture: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run Build
        run: |
          docker build -t ${{matrix.architecture}}  --pull --no-cache .
      - name: Build and push Docker image
        run: |
          docker tag ${{matrix.architecture}} $ORGANIZATION/$REPO-arch:arch-${{matrix.architecture}}-${{github.event.inputs.tag || github.ref_name}}
          docker push $ORGANIZATION/$REPO-arch:arch-${{matrix.architecture}}-${{github.event.inputs.tag || github.ref_name}}

  build-arm64:
    runs-on: sh-ubuntu-24.04-arm 
    permissions:
      contents: write
    strategy:
      matrix:
        architecture: [arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run Build
        run: |
          docker build -t ${{matrix.architecture}} --pull --no-cache .
      - name: Build and push Docker image
        run: |
          docker tag ${{matrix.architecture}} $ORGANIZATION/$REPO-arch:arch-${{matrix.architecture}}-${{github.event.inputs.tag || github.ref_name}}
          docker push $ORGANIZATION/$REPO-arch:arch-${{matrix.architecture}}-${{github.event.inputs.tag || github.ref_name}}

  create-manifest:
    runs-on: ubuntu-24.04
    needs: [build-amd64, build-arm64]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create and push multi-arch manifest
        run: |
          docker manifest create $ORGANIZATION/$REPO:${{ github.event.inputs.tag || github.ref_name }} \
            $ORGANIZATION/$REPO-arch:arch-amd64-${{github.event.inputs.tag || github.ref_name}} \
            $ORGANIZATION/$REPO-arch:arch-arm64-${{github.event.inputs.tag || github.ref_name}}
          docker manifest push $ORGANIZATION/$REPO:${{ github.event.inputs.tag || github.ref_name }}
      - name: Create and push latest manifest
        run: |
          docker manifest create $ORGANIZATION/$REPO:latest \
            $ORGANIZATION/$REPO-arch:arch-amd64-${{github.event.inputs.tag || github.ref_name}} \
            $ORGANIZATION/$REPO-arch:arch-arm64-${{github.event.inputs.tag || github.ref_name}}
          docker manifest push $ORGANIZATION/$REPO:latest

      # After we build the Docker image, we create a pull request to update the GitOps repository
      # This will allow us to update the Helm chart with the new Docker image tag.
      - name: Create GitOps Pull Request
        uses: cedricve/gitops-pullrequest-action@master
        with:
          github-token: ${{ secrets.TOKEN }}
          gitops-repo: "uug-ai/gitops"
          gitops-file: "environments/staging/kerberos-hub/values.yaml"
          gitops-pr-branch: "release-${{ env.REPO }}-${{ github.event.inputs.tag || github.ref_name }}"
          gitops-key: "kerberospipeline.${{ env.REPO_SHORT }}.tag"
          gitops-value: "${{ github.event.inputs.tag || github.ref_name }}"
          commit-email: "gitops@uug.ai"
          commit-name: "GitOps - UUG.AI"
          commit-message: "A new release for Kerberos Hub Pipeline ${{ env.REPO_SHORT }} - ${{ github.event.inputs.tag || github.ref_name }}"