name: Create a new release
on:
  release:
    types: [created]

env:
  ORGANIZATION: uugai
  PROJECT: ${{ github.event.repository.name }}

jobs:

  build-amd64:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    strategy:
      matrix:
        architecture: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run Build
        run: |
          docker build -t ${{matrix.architecture}}  --pull --no-cache .
      - name: Build and push Docker image
        run: |
          docker tag ${{matrix.architecture}} $ORGANIZATION/$PROJECT-arch:arch-${{matrix.architecture}}-${{github.event.inputs.tag || github.ref_name}}
          docker push $ORGANIZATION/$PROJECT-arch:arch-${{matrix.architecture}}-${{github.event.inputs.tag || github.ref_name}}

  build-arm64:
    runs-on: sh-ubuntu-24.04-arm 
    permissions:
      contents: write
    strategy:
      matrix:
        architecture: [arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run Build
        run: |
          docker build -t ${{matrix.architecture}} --pull --no-cache .
      - name: Build and push Docker image
        run: |
          docker tag ${{matrix.architecture}} $ORGANIZATION/$PROJECT-arch:arch-${{matrix.architecture}}-${{github.event.inputs.tag || github.ref_name}}
          docker push $ORGANIZATION/$PROJECT-arch:arch-${{matrix.architecture}}-${{github.event.inputs.tag || github.ref_name}}

  create-manifest:
    runs-on: ubuntu-24.04
    needs: [build-amd64, build-arm64]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Create and push multi-arch manifest
        run: |
          docker manifest create $ORGANIZATION/$PROJECT:${{ github.event.inputs.tag || github.ref_name }} \
            $ORGANIZATION/$PROJECT-arch:arch-amd64-${{github.event.inputs.tag || github.ref_name}} \
            $ORGANIZATION/$PROJECT-arch:arch-arm64-${{github.event.inputs.tag || github.ref_name}}
          docker manifest push $ORGANIZATION/$PROJECT:${{ github.event.inputs.tag || github.ref_name }}
      - name: Create and push latest manifest
        run: |
          docker manifest create $ORGANIZATION/$PROJECT:latest \
            $ORGANIZATION/$PROJECT-arch:arch-amd64-${{github.event.inputs.tag || github.ref_name}} \
            $ORGANIZATION/$PROJECT-arch:arch-arm64-${{github.event.inputs.tag || github.ref_name}}
          docker manifest push $ORGANIZATION/$PROJECT:latest

      # After we build the Docker image, we create a pull request to update the GitOps repository
      # This will allow us to update the Helm chart with the new Docker image tag.
      - name: Create GitOps Pull Request
        uses: cedricve/gitops-pullrequest-action@master
        with:
          github-token: ${{ secrets.TOKEN }}
          gitops-repo: "uug-ai/gitops"
          gitops-file: "environments/staging/${{ env.PROJECT }}/deployment.yaml"
          gitops-pr-branch: "release-${{ env.PROJECT }}-${{ github.event.inputs.tag || github.ref_name }}"
          gitops-key: ".spec.template.spec.containers[0].image"
          gitops-value: "${{ github.event.inputs.tag || github.ref_name }}"
          commit-email: "gitops@uug.ai"
          commit-name: "GitOps - UUG.AI"
          commit-message: "A new release for ${{ env.PROJECT }} - ${{ github.event.inputs.tag || github.ref_name }}"